#!/bin/bash
# Builds the Swift package and wraps the executable in a proper .app bundle
# that runs as a menu-bar-only agent (no Dock icon).
set -euo pipefail

cd "$(dirname "$0")"

APP_NAME="GitHub Workflows"
BIN_NAME="WorkflowsMenuBar"
BUNDLE_ID="com.workflowsmenubar.app"

# Inject the OAuth Client ID at build time if provided (overrides Config.swift).
GEN="Sources/WorkflowsMenuBar/Config.generated.swift"
if [ -n "${GH_CLIENT_ID:-}" ]; then
    echo "▸ Injecting GH_CLIENT_ID into the build…"
    cat > "$GEN" <<GENEOF
// Auto-generated by build-app.sh — do not edit.
enum GeneratedConfig {
    static let injectedClientID = "${GH_CLIENT_ID}"
}
GENEOF
fi

# Generate the app icon if it isn't built yet.
if [ ! -f build/AppIcon.icns ]; then
    echo "▸ Generating app icon…"
    ./make-icon.sh
fi

echo "▸ Building release binary…"
swift build -c release
BIN_PATH="$(swift build -c release --show-bin-path)/$BIN_NAME"

APP_DIR="build/$APP_NAME.app"
MACOS_DIR="$APP_DIR/Contents/MacOS"
RES_DIR="$APP_DIR/Contents/Resources"

echo "▸ Assembling ${APP_DIR}…"
rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RES_DIR"
cp "$BIN_PATH" "$MACOS_DIR/$BIN_NAME"
cp build/AppIcon.icns "$RES_DIR/AppIcon.icns"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>$APP_NAME</string>
    <key>CFBundleDisplayName</key><string>$APP_NAME</string>
    <key>CFBundleExecutable</key><string>$BIN_NAME</string>
    <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# Ad-hoc code signature so macOS keychain access works without re-prompting endlessly.
echo "▸ Code signing (ad-hoc)…"
codesign --force --deep --sign - "$APP_DIR" >/dev/null 2>&1 || echo "  (codesign skipped)"

echo "✓ Built: $APP_DIR"
echo "  Run it:   open \"$APP_DIR\""
echo "  Install:  cp -r \"$APP_DIR\" /Applications/"
